name: TEST3
permissions:
  contents: read

on: [push, pull_request]

jobs:
  upload-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: ls -a

      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v4
        with:
          name: pr
          path: pr/
