name: E2E Tester
permissions:
  contents: read

on:
  workflow_run:
    workflows: ["Debug ENV and SECRET"]
    types: ["completed"]


jobs:
  debug-repo:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: ls -a


      - name: Test and Debug
        run: |
          echo "REP_VAR=${{ vars.REP_VAR }}"
          echo "REP_SECRET=${{ secrets.REP_SECRET }}"

  debug-env:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: test-env
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: ls -a

      - name: Test and Debug (test-env)
        run: |
          echo "ENV_VAR=${{ vars.TEST_ENV_VAR }}"
          echo "ENV_SECRET=${{ secrets.TEST_ENV_SECRET }}"